#include <furi.h>
#include <string.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/submenu.h>
#include <gui/modules/variable_item_list.h>
#include <gui/modules/widget.h>

/* generated by fbt from .png files in images folder */
#include <alcohol_calc_icons.h>

typedef enum {
    AlcoholCalcViewMenu,
    AlcoholCalcViewDilute,
    AlcoholCalcViewMix,
    AlcoholCalcViewTarget,
    AlcoholCalcViewAbout,
} AlcoholCalcView;

#define DEGREE_COUNT 100 /* 1..100 */
#define VOLUME_COUNT 250 /* 0.1 .. 25.0, step 0.1 */

/* Holding Left/Right for longer than ACCEL_HOLD_MS speeds up the step size,
   so decimal-heavy fields like Volume don't take forever to scroll through. */
#define ACCEL_HOLD_MS 1500
#define ACCEL_REPEAT_GAP_MS 400

typedef struct {
    uint32_t last_tick;
    uint32_t hold_start_tick;
} AccelState;

static uint8_t
    apply_accel(AccelState* accel, uint8_t old_idx, uint8_t raw_idx, uint8_t max_idx, uint8_t accel_step) {
    uint32_t now = furi_get_tick();
    int32_t dir = 0;
    if(raw_idx > old_idx) dir = 1;
    else if(raw_idx < old_idx) dir = -1;

    if(dir == 0) {
        accel->last_tick = now;
        accel->hold_start_tick = now;
        return raw_idx;
    }

    if(now - accel->last_tick > ACCEL_REPEAT_GAP_MS) {
        accel->hold_start_tick = now;
    }
    accel->last_tick = now;

    int32_t step = (now - accel->hold_start_tick > ACCEL_HOLD_MS) ? accel_step : 1;

    int32_t result = (int32_t)old_idx + dir * step;
    if(result < 0) result = 0;
    if(result > (int32_t)max_idx) result = (int32_t)max_idx;
    return (uint8_t)result;
}

typedef struct {
    Gui* gui;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;

    VariableItemList* dilute_list;
    VariableItemList* mix_list;
    VariableItemList* target_list;
    Widget* about_widget;

    /* Dilute: spirit + water -> lower degree */
    uint8_t d_before_idx;
    uint8_t d_after_idx;
    uint8_t d_volume_idx;
    AccelState d_before_accel;
    AccelState d_after_accel;
    AccelState d_volume_accel;
    VariableItem* d_water_item;
    VariableItem* d_total_item;

    /* Mix: two ready drinks -> resulting volume/degree */
    uint8_t m_v1_idx;
    uint8_t m_c1_idx;
    uint8_t m_v2_idx;
    uint8_t m_c2_idx;
    AccelState m_v1_accel;
    AccelState m_c1_accel;
    AccelState m_v2_accel;
    AccelState m_c2_accel;
    VariableItem* m_total_v_item;
    VariableItem* m_total_c_item;

    /* Target: desired volume/degree from spirit -> water/spirit needed */
    uint8_t t_volume_idx;
    uint8_t t_degree_idx;
    uint8_t t_spirit_idx;
    AccelState t_volume_accel;
    AccelState t_degree_accel;
    AccelState t_spirit_accel;
    VariableItem* t_spirit_item;
    VariableItem* t_water_item;
} AlcoholCalcApp;

static float volume_from_idx(uint8_t idx) {
    return ((float)idx + 1.0f) * 0.1f;
}

static uint8_t idx_from_volume(float volume) {
    int idx = (int)(volume * 10.0f + 0.5f) - 1;
    if(idx < 0) idx = 0;
    if(idx > VOLUME_COUNT - 1) idx = VOLUME_COUNT - 1;
    return (uint8_t)idx;
}

static uint8_t degree_from_idx(uint8_t idx) {
    return idx + 1;
}

/* ---------- Dilute screen ---------- */

static void dilute_recalculate(AlcoholCalcApp* app) {
    float before = degree_from_idx(app->d_before_idx);
    float after = degree_from_idx(app->d_after_idx);
    float volume = volume_from_idx(app->d_volume_idx);
    char buf[16];

    if(before <= after) {
        variable_item_set_current_value_text(app->d_water_item, "need stronger");
        variable_item_set_current_value_text(app->d_total_item, "-");
        return;
    }

    float water = volume * (before - after) / after;
    float total = volume + water;

    snprintf(buf, sizeof(buf), "%.2f L", (double)water);
    variable_item_set_current_value_text(app->d_water_item, buf);

    snprintf(buf, sizeof(buf), "%.2f L", (double)total);
    variable_item_set_current_value_text(app->d_total_item, buf);
}

static void dilute_before_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->d_before_idx = apply_accel(&app->d_before_accel, app->d_before_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->d_before_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->d_before_idx));
    variable_item_set_current_value_text(item, buf);
    dilute_recalculate(app);
}

static void dilute_after_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->d_after_idx = apply_accel(&app->d_after_accel, app->d_after_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->d_after_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->d_after_idx));
    variable_item_set_current_value_text(item, buf);
    dilute_recalculate(app);
}

static void dilute_volume_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->d_volume_idx = apply_accel(&app->d_volume_accel, app->d_volume_idx, raw, VOLUME_COUNT - 1, 10);
    variable_item_set_current_value_index(item, app->d_volume_idx);
    char buf[12];
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->d_volume_idx));
    variable_item_set_current_value_text(item, buf);
    dilute_recalculate(app);
}

static uint32_t alcohol_calc_navigate_to_menu(void* context) {
    UNUSED(context);
    return AlcoholCalcViewMenu;
}

static void alcohol_calc_build_dilute_view(AlcoholCalcApp* app) {
    VariableItemList* list = app->dilute_list;
    VariableItem* item;
    char buf[16];

    app->d_before_idx = 95; /* 96 */
    app->d_after_idx = 39; /* 40 */
    app->d_volume_idx = idx_from_volume(10.0f);

    item = variable_item_list_add(list, "Before, %", DEGREE_COUNT, dilute_before_changed, app);
    variable_item_set_current_value_index(item, app->d_before_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->d_before_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "After, %", DEGREE_COUNT, dilute_after_changed, app);
    variable_item_set_current_value_index(item, app->d_after_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->d_after_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Volume", VOLUME_COUNT, dilute_volume_changed, app);
    variable_item_set_current_value_index(item, app->d_volume_idx);
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->d_volume_idx));
    variable_item_set_current_value_text(item, buf);

    app->d_water_item = variable_item_list_add(list, "Add water", 1, NULL, app);
    app->d_total_item = variable_item_list_add(list, "Total vol", 1, NULL, app);

    dilute_recalculate(app);

    view_set_previous_callback(variable_item_list_get_view(list), alcohol_calc_navigate_to_menu);
}

/* ---------- Mix screen ---------- */

static void mix_recalculate(AlcoholCalcApp* app) {
    float v1 = volume_from_idx(app->m_v1_idx);
    float c1 = degree_from_idx(app->m_c1_idx);
    float v2 = volume_from_idx(app->m_v2_idx);
    float c2 = degree_from_idx(app->m_c2_idx);
    char buf[16];

    float total_v = v1 + v2;
    float total_c = (v1 * c1 + v2 * c2) / total_v;

    snprintf(buf, sizeof(buf), "%.2f L", (double)total_v);
    variable_item_set_current_value_text(app->m_total_v_item, buf);

    snprintf(buf, sizeof(buf), "%.1f%%", (double)total_c);
    variable_item_set_current_value_text(app->m_total_c_item, buf);
}

static void mix_v1_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->m_v1_idx = apply_accel(&app->m_v1_accel, app->m_v1_idx, raw, VOLUME_COUNT - 1, 10);
    variable_item_set_current_value_index(item, app->m_v1_idx);
    char buf[12];
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->m_v1_idx));
    variable_item_set_current_value_text(item, buf);
    mix_recalculate(app);
}

static void mix_c1_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->m_c1_idx = apply_accel(&app->m_c1_accel, app->m_c1_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->m_c1_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->m_c1_idx));
    variable_item_set_current_value_text(item, buf);
    mix_recalculate(app);
}

static void mix_v2_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->m_v2_idx = apply_accel(&app->m_v2_accel, app->m_v2_idx, raw, VOLUME_COUNT - 1, 10);
    variable_item_set_current_value_index(item, app->m_v2_idx);
    char buf[12];
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->m_v2_idx));
    variable_item_set_current_value_text(item, buf);
    mix_recalculate(app);
}

static void mix_c2_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->m_c2_idx = apply_accel(&app->m_c2_accel, app->m_c2_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->m_c2_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->m_c2_idx));
    variable_item_set_current_value_text(item, buf);
    mix_recalculate(app);
}

static void alcohol_calc_build_mix_view(AlcoholCalcApp* app) {
    VariableItemList* list = app->mix_list;
    VariableItem* item;
    char buf[16];

    app->m_v1_idx = idx_from_volume(10.0f);
    app->m_c1_idx = 95; /* 96 */
    app->m_v2_idx = idx_from_volume(10.0f);
    app->m_c2_idx = 39; /* 40 */

    item = variable_item_list_add(list, "Volume 1", VOLUME_COUNT, mix_v1_changed, app);
    variable_item_set_current_value_index(item, app->m_v1_idx);
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->m_v1_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Strength 1", DEGREE_COUNT, mix_c1_changed, app);
    variable_item_set_current_value_index(item, app->m_c1_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->m_c1_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Volume 2", VOLUME_COUNT, mix_v2_changed, app);
    variable_item_set_current_value_index(item, app->m_v2_idx);
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->m_v2_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Strength 2", DEGREE_COUNT, mix_c2_changed, app);
    variable_item_set_current_value_index(item, app->m_c2_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->m_c2_idx));
    variable_item_set_current_value_text(item, buf);

    app->m_total_v_item = variable_item_list_add(list, "Total vol", 1, NULL, app);
    app->m_total_c_item = variable_item_list_add(list, "Total %", 1, NULL, app);

    mix_recalculate(app);

    view_set_previous_callback(variable_item_list_get_view(list), alcohol_calc_navigate_to_menu);
}

/* ---------- Target screen ---------- */

static void target_recalculate(AlcoholCalcApp* app) {
    float volume = volume_from_idx(app->t_volume_idx);
    float degree = degree_from_idx(app->t_degree_idx);
    float spirit = degree_from_idx(app->t_spirit_idx);
    char buf[16];

    if(spirit < degree) {
        variable_item_set_current_value_text(app->t_spirit_item, "need stronger");
        variable_item_set_current_value_text(app->t_water_item, "-");
        return;
    }

    float v_spirit = volume * degree / spirit;
    float v_water = volume - v_spirit;

    snprintf(buf, sizeof(buf), "%.2f L", (double)v_spirit);
    variable_item_set_current_value_text(app->t_spirit_item, buf);

    snprintf(buf, sizeof(buf), "%.2f L", (double)v_water);
    variable_item_set_current_value_text(app->t_water_item, buf);
}

static void target_volume_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->t_volume_idx = apply_accel(&app->t_volume_accel, app->t_volume_idx, raw, VOLUME_COUNT - 1, 10);
    variable_item_set_current_value_index(item, app->t_volume_idx);
    char buf[12];
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->t_volume_idx));
    variable_item_set_current_value_text(item, buf);
    target_recalculate(app);
}

static void target_degree_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->t_degree_idx = apply_accel(&app->t_degree_accel, app->t_degree_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->t_degree_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->t_degree_idx));
    variable_item_set_current_value_text(item, buf);
    target_recalculate(app);
}

static void target_spirit_changed(VariableItem* item) {
    AlcoholCalcApp* app = variable_item_get_context(item);
    uint8_t raw = variable_item_get_current_value_index(item);
    app->t_spirit_idx = apply_accel(&app->t_spirit_accel, app->t_spirit_idx, raw, DEGREE_COUNT - 1, 5);
    variable_item_set_current_value_index(item, app->t_spirit_idx);
    char buf[8];
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->t_spirit_idx));
    variable_item_set_current_value_text(item, buf);
    target_recalculate(app);
}

static void alcohol_calc_build_target_view(AlcoholCalcApp* app) {
    VariableItemList* list = app->target_list;
    VariableItem* item;
    char buf[16];

    app->t_volume_idx = idx_from_volume(10.0f);
    app->t_degree_idx = 39; /* 40 */
    app->t_spirit_idx = 95; /* 96 */

    item = variable_item_list_add(list, "Need volume", VOLUME_COUNT, target_volume_changed, app);
    variable_item_set_current_value_index(item, app->t_volume_idx);
    snprintf(buf, sizeof(buf), "%.1f L", (double)volume_from_idx(app->t_volume_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Need %", DEGREE_COUNT, target_degree_changed, app);
    variable_item_set_current_value_index(item, app->t_degree_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->t_degree_idx));
    variable_item_set_current_value_text(item, buf);

    item = variable_item_list_add(list, "Spirit %", DEGREE_COUNT, target_spirit_changed, app);
    variable_item_set_current_value_index(item, app->t_spirit_idx);
    snprintf(buf, sizeof(buf), "%u%%", degree_from_idx(app->t_spirit_idx));
    variable_item_set_current_value_text(item, buf);

    app->t_spirit_item = variable_item_list_add(list, "Take spirit", 1, NULL, app);
    app->t_water_item = variable_item_list_add(list, "Take water", 1, NULL, app);

    target_recalculate(app);

    view_set_previous_callback(variable_item_list_get_view(list), alcohol_calc_navigate_to_menu);
}

/* ---------- About screen ---------- */

static void alcohol_calc_build_about_view(AlcoholCalcApp* app) {
    widget_add_text_box_element(
        app->about_widget,
        0,
        0,
        128,
        64,
        AlignCenter,
        AlignTop,
        "\e#Alcohol Calc\e#\n"
        "Spirit dilution & mixing calculator for Flipper Zero.\n\n"
        "github.com/vtlklr",
        false);

    view_set_previous_callback(widget_get_view(app->about_widget), alcohol_calc_navigate_to_menu);
}

/* ---------- Menu / app lifecycle ---------- */

static void alcohol_calc_submenu_callback(void* context, uint32_t index) {
    AlcoholCalcApp* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, index);
}

static bool alcohol_calc_navigation_event_callback(void* context) {
    AlcoholCalcApp* app = context;
    view_dispatcher_stop(app->view_dispatcher);
    return true;
}

static AlcoholCalcApp* alcohol_calc_app_alloc(void) {
    AlcoholCalcApp* app = malloc(sizeof(AlcoholCalcApp));
    memset(app, 0, sizeof(AlcoholCalcApp));

    app->gui = furi_record_open(RECORD_GUI);
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, alcohol_calc_navigation_event_callback);

    app->submenu = submenu_alloc();
    submenu_add_item(
        app->submenu, "Dilute spirit", AlcoholCalcViewDilute, alcohol_calc_submenu_callback, app);
    submenu_add_item(
        app->submenu, "Mix two spirits", AlcoholCalcViewMix, alcohol_calc_submenu_callback, app);
    submenu_add_item(
        app->submenu,
        "Target volume",
        AlcoholCalcViewTarget,
        alcohol_calc_submenu_callback,
        app);
    submenu_add_item(
        app->submenu, "About", AlcoholCalcViewAbout, alcohol_calc_submenu_callback, app);
    view_dispatcher_add_view(app->view_dispatcher, AlcoholCalcViewMenu, submenu_get_view(app->submenu));

    app->dilute_list = variable_item_list_alloc();
    alcohol_calc_build_dilute_view(app);
    view_dispatcher_add_view(
        app->view_dispatcher, AlcoholCalcViewDilute, variable_item_list_get_view(app->dilute_list));

    app->mix_list = variable_item_list_alloc();
    alcohol_calc_build_mix_view(app);
    view_dispatcher_add_view(
        app->view_dispatcher, AlcoholCalcViewMix, variable_item_list_get_view(app->mix_list));

    app->target_list = variable_item_list_alloc();
    alcohol_calc_build_target_view(app);
    view_dispatcher_add_view(
        app->view_dispatcher, AlcoholCalcViewTarget, variable_item_list_get_view(app->target_list));

    app->about_widget = widget_alloc();
    alcohol_calc_build_about_view(app);
    view_dispatcher_add_view(
        app->view_dispatcher, AlcoholCalcViewAbout, widget_get_view(app->about_widget));

    view_dispatcher_attach_to_gui(app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    view_dispatcher_switch_to_view(app->view_dispatcher, AlcoholCalcViewMenu);

    return app;
}

static void alcohol_calc_app_free(AlcoholCalcApp* app) {
    view_dispatcher_remove_view(app->view_dispatcher, AlcoholCalcViewMenu);
    view_dispatcher_remove_view(app->view_dispatcher, AlcoholCalcViewDilute);
    view_dispatcher_remove_view(app->view_dispatcher, AlcoholCalcViewMix);
    view_dispatcher_remove_view(app->view_dispatcher, AlcoholCalcViewTarget);
    view_dispatcher_remove_view(app->view_dispatcher, AlcoholCalcViewAbout);

    submenu_free(app->submenu);
    variable_item_list_free(app->dilute_list);
    variable_item_list_free(app->mix_list);
    variable_item_list_free(app->target_list);
    widget_free(app->about_widget);

    view_dispatcher_free(app->view_dispatcher);
    furi_record_close(RECORD_GUI);

    free(app);
}

int32_t alcohol_calc_app(void* p) {
    UNUSED(p);
    AlcoholCalcApp* app = alcohol_calc_app_alloc();

    view_dispatcher_run(app->view_dispatcher);

    alcohol_calc_app_free(app);
    return 0;
}
